# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSuiteAppCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('app_credential', jsonfield.fields.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.TextField(blank=True)),
                ('attachment_id', models.TextField(blank=True)),
                ('history_id', models.CharField(blank=True, max_length=30)),
                ('thread_id', models.CharField(blank=True, max_length=30)),
                ('thread_topic', models.CharField(blank=True, max_length=500)),
                ('message_id', models.CharField(blank=True, max_length=30)),
                ('email_from', models.TextField(blank=True)),
                ('email_to', models.TextField(blank=True)),
                ('email_cc', models.TextField(blank=True)),
                ('email_bcc', models.TextField(blank=True)),
                ('subject', models.TextField(blank=True)),
                ('labels', models.CharField(blank=True, max_length=1000)),
                ('date', models.DateTimeField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('html', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
