# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20180224_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('mark-read', 'Mark as read'), ('mark-unread', 'Mark as unread'), ('mark-read', 'Archive message'), ('add-label', 'Add label')], max_length=30)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('email_from', 'From'), ('email_to', 'To'), ('subject', 'Subject'), ('text', 'Message'), ('date', 'Date Received')], max_length=30)),
                ('predicate', models.CharField(choices=[('contains', 'Contains'), ('does-not-contain', 'Does not contain'), ('equals', 'Equals'), ('does-not-equal', 'Does not equal'), ('lt', 'Less than'), ('gt', 'Greater than')], max_length=30)),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actions', models.ManyToManyField(to='mails.Action')),
                ('rules', models.ManyToManyField(to='mails.Condition')),
            ],
        ),
        migrations.DeleteModel(
            name='GSuiteAppCredential',
        ),
    ]
