# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_auto_20180226_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='predicate_quantifier',
            field=models.CharField(choices=[('all', 'All'), ('any', 'Any')], default=None, max_length=5),
            preserve_default=False,
        ),
    ]
